### Pandas

In [1]:
import pandas as pd
import numpy as np

<p>numpy.fromfile(file, dtype=float, count=-1, sep='', offset=0)<br>
Construct an array from data in a text or binary file.

A highly efficient way of reading binary data with a known data-type, as well as parsing simply formatted text files. Data written using the tofile method can be read using this function.<p>

### Creating a DataFrame

In [2]:
# Import pandas library 
import pandas as pd 
  
# initialize list of lists 
data = [['tom', 10], ['nick', 15], ['juli', 14]] 
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['Name', 'Age']) 
  
# print dataframe. 
df 

Name  Age
0   tom   10
1  nick   15
2  juli   14

In [3]:
# intialise data of lists. 
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]} 
  
# Create DataFrame 
df = pd.DataFrame(data) 
  
# Print the output. 
df 

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [4]:
# initialise data of lists. 
data = {'Name':['Tom', 'Jack', 'nick', 'juli'], 'marks':[99, 98, 95, 90]} 
  
# Creates pandas DataFrame. 
df = pd.DataFrame(data, index =['rank1', 'rank2', 'rank3', 'rank4']) 
  
# print the data 
df 

Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

### Adding a Column to the DataFrame

In [5]:
df["gender"]=["Male","Male","Female","Female"]

In [6]:
df

Name  marks  gender
rank1   Tom     99    Male
rank2  Jack     98    Male
rank3  nick     95  Female
rank4  juli     90  Female

In [7]:
N=np.arange(8).reshape(4,2)
print(N)
print(np.sum(N,axis=1))

#np.sum(N,axis=1)
#we can see each set represent a row so it when axis=0 it has to be something to do with this set, wait..... shit
#but this is wrong its the other way but i found other one you remember how shape returns the dimensions here it is (4,2) 0-axis
#has to do something about first entry see it worked out


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[ 1  5  9 13]


In [8]:
np.diag(N.T)

array([0, 3])

In [9]:
N1=np.arange(2*3*4).reshape(2,3,4)
print(N1)
print(np.sum(N1,axis=0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


#### Important
- Axes=0 (Row, X-axis)
- Axes=1 (Column, Y-axis)
- Keepdims=True(Does not change the matrix dimension---usually matrix gets transformed to rank 1 matrix when they perform transformations which cahnages them to simple vectors like np.sum())

In [10]:
iris=pd.read_csv("iris.csv")

In [11]:
iris.index.name='id'

In [12]:
iris.index=iris["Id"]

In [13]:
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
Id                                                                   
1      1            5.1           3.5            1.4           0.2   
2      2            4.9           3.0            1.4           0.2   
3      3            4.7           3.2            1.3           0.2   
4      4            4.6           3.1            1.5           0.2   
5      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  146            6.7           3.0            5.2           2.3   
147  147            6.3           2.5            5.0           1.9   
148  148            6.5           3.0            5.2           2.0   
149  149            6.2           3.4            5.4           2.3   
150  150            5.9           3.0            5.1           1.8   

            Species  
Id                   
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
..              ...  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150  Iris-virginica  

[150 rows x 6 columns]

Drop in pandas is used to drop the elements from the dataframe, and axis tells us the direction of the  elemention

In [14]:
iris.drop(['Id'],axis=1)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

There are many ways to select a subset of your data. The Pandas Micro-Course(https://www.kaggle.com/learn/pandas) covers these in more depth, but we will focus on two approaches for now.

- Dot notation, which we use to select the "prediction target"
- Selecting with a column list, which we use to select the "features"

### Selecting The Prediction Target
You can pull out a variable with dot-notation. This single column is stored in a Series, which is broadly like a DataFrame with only a single column of data.

We'll use the dot notation to select the column we want to predict, which is called the prediction target. By convention, the prediction target is called y. So the code we need to save the house prices in the Melbourne data is

In [15]:
y=iris.Species

### Choosing "Features"
We select multiple features by providing a list of column names inside brackets. Each item in that list should be a string

In [16]:
features=["SepalLengthCm","PetalLengthCm"]

In [17]:
iris = iris.rename(columns = {"Id":"Mod_col"}) 

In [18]:
#Create a dataFrame using dictionary 
df=pd.DataFrame({"Name":['Tom','Nick','John','Peter'], 
                 "Age":[15,26,17,28]}) 

# Change the column names 
df.columns =['Col_1', 'Col_2'] 
  
# Change the row indexes 
df.index = ['Row_1', 'Row_2', 'Row_3', 'Row_4'] 

- Errors to avoid while adding a new column to the DataFrame

<img src="add_new_column.png" alt="miley face">

In [19]:
#one hot encoding
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [20]:
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_
enc.transform([['Female', 1], ['Male', 4]]).toarray()
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
#enc.get_feature_names(['gender', 'group'])
#array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],dtype=object)
#drop_enc = OneHotEncoder(drop='first').fit(X)
#drop_enc.categories_
#drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()

array([['Male', 1],
       [None, 2]], dtype=object)

In [21]:
X=np.array([["Male",7,1,5,6],["Female",5.0,559,232,6565],["Male",54,878,545,878],["Male",454,87,8564,45]])

In [22]:
X_LabelEncoding=X.copy()

In [23]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
X_LabelEncoding[:,0]=le.fit_transform(X_LabelEncoding[:,0])

In [24]:
X_LabelEncoding #transformed 

array([['1', '7', '1', '5', '6'],
       ['0', '5.0', '559', '232', '6565'],
       ['1', '54', '878', '545', '878'],
       ['1', '454', '87', '8564', '45']], dtype='<U6')

In [25]:
#one hot encoding through pandas
X_dummies=pd.get_dummies(X[:,0])
X_dummies

Female  Male
0       0     1
1       1     0
2       0     1
3       0     1

In [26]:
columns=["Gender","rand1","rand2","buddi","buddi"]
sample=pd.DataFrame(data=X[0:,0:],columns=columns)  

In [27]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Gender", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(sample)

labelencoder_X = LabelEncoder()


In [28]:
sample[:,] = labelencoder_X.fit_transform(sample[:, 2])

TypeError: '(slice(None, None, None), 2)' is an invalid key

In [29]:
ohe=OneHotEncoder(X[:,0])
ohe.fit_transform(X[:,0])

c:\users\ranad\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass categories=[0.0 0.0 0.0 1.0] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


ValueError: Expected 2D array, got 1D array instead:
array=[0.0 0.0 0.0 1.0].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [33]:
#Reading excel sheet data
bdata=pd.read_excel("bigdata.xlsx")

In [ ]:
sum=0
val=0
for i in range(13):
    print(bdata.iloc[i*6,1]*bdata.iloc[i*6,15])
    val+=bdata.iloc[i*6,1]
    sum+=bdata.iloc[i*6,15]
print("total number of cities: "+str(sum))
print("value:"+str(val/sum))

## Series

sort_index() sorts the data with indexes values

In [34]:
X=np.array([[4,4,1],[0,2,1],[2,1,0]])

In [36]:
#np.linalg.inv(X) ### There is a reason(rows are dependent)

In [37]:
A=np.array([[1,2,3,4,5],[11,12,13,14,15]])
for i in A:
    print(list(i[1:3]))

[2, 3]
[12, 13]


In [38]:
import pickle 
  
def storeData(): 
    # initializing data to be stored in db 
    Omkar = {'key' : 'Omkar', 'name' : 'Omkar Pathak', 
    'age' : 21, 'pay' : 40000} 
    Jagdish = {'key' : 'Jagdish', 'name' : 'Jagdish Pathak', 
    'age' : 50, 'pay' : 50000} 
  
    # database 
    db = {} 
    db['Omkar'] = Omkar 
    db['Jagdish'] = Jagdish 
      
    # Its important to use binary mode 
    dbfile = open('examplePickle', 'ab') 
      
    # source, destination 
    pickle.dump(db, dbfile)                      
    dbfile.close() 
  
def loadData(): 
    # for reading also binary mode is important 
    dbfile = open('examplePickle', 'rb')      
    db = pickle.load(dbfile) 
    for keys in db: 
        print(keys, '=>', db[keys]) 
    dbfile.close() 
  
if __name__ == '__main__': 
    storeData() 
    loadData() 

Omkar => {'key': 'Omkar', 'name': 'Omkar Pathak', 'age': 21, 'pay': 40000}
Jagdish => {'key': 'Jagdish', 'name': 'Jagdish Pathak', 'age': 50, 'pay': 50000}


In [ ]:
np.set_printoptions(linewidth=200)

<p>The above line of code sets the how many lines to print </p>

In [ ]:
path=r"C:\Users\ranad\Desktop\Sche\Data Analysis\Fashion MNIST"
fashMnist=pd.read_csv(path+"\\fashion-mnist_train.csv")

In [ ]:
fashMnist

In [ ]:
import matplotlib.pyplot as plt
np.set_printoptions(linewidth=200)
index=42
ind=fashMnist.iloc[index,1:785]
ind=ind.to_numpy().reshape(28,28)
plt.imshow(ind)
print(ind)
print(fashMnist.iloc[index,784])

In [ ]:
fashMnist.compile(optimizer = tf.optimizers.Adam(),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
fashMnist.fit(training_images, training_labels, epochs=5)